apiVersion: v1
kind: Service
metadata: 
  name: portfollio-service 
  namespace: ns-3
  labels:
    app: flask-app
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30271
  type: NodePort
