apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-configmap 
  namespace: tm-ns
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: tourism_db
  MONGO_HOST: mongo-service
  
   