kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  namespace: tm-ns
spec:
  selector:
    app: mongo-statefulset
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP