kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset 
  namespace: tm-ns
spec: 
  selector:
    matchLabels:
      app: mysql-statefulset
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-statefulset
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: tourism_db
        - name: MYSQL_ROOT_HOST
          value: "%"
        command: ["mysqld"]
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
