apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tm-ns
spec:
  selector:
    app: mysql-statefulset
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP