apiVersion: v1
kind: Service
metadata:
  name: node-app-service 
  namespace: ns-1
spec:
  selector:
    app: blog-app
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
     nodePort: 30721
  type: NodePort