apiVersion: v1
kind: Service
metadata:
  name: file-manager-servie
  namespace: file-manager-ns
spec: 
  selector:
    app: file-manager-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30112
  type: NodePort