apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog-deployment
  namespace: flask-blog-ns
spec:
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata: 
      labels:
        app: blog-app
    spec:
      containers:
        - name: flask-blog-app
          image: manodayahire/flask-blog-app
          ports:
            - containerPort: 5000