apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
  namespace: flask-blog-ns
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30140
  type: NodePort