apiVersion: v1
kind: Service 
metadata:
  name: app-service
  namespace: wm-ns
spec:
  selector:
    app: worker-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
    