kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  namespace: em-ns
spec: 
  selector:
    db: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP