apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset 
  namespace: em-ns
spec:
  selector:
    matchLabels:
      db: mysql
  replicas: 1
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: em-config
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: em-config
                  key: MYSQL_DATABASE
