apiVersion: v1
kind: Service
metadata:   
  name: app-service 
  namespace: restro-nss
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30012

  selector:
    app: restro-app
  type: NodePort
