apiVersion: apps/v1
kind: Deployment
metadata:
  name: placement-deployment
  namespace: ps-ns
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: placement-app
  template:
    metadata: 
      labels:
        app: placement-app
    spec:
      containers:
      - name: placement-container
        image: manodayahire/placement-system:latest
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ps-configmap
                key: DB_HOST

          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: ps-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ps-configmap
                key: DB_PASSWORD

          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: ps-configmap
                key: DB_NAME