apiVersion: v1
kind: Service 
metadata:
  name: ps-service
  namespace: ps-ns 
spec: 
  selector:
    app: placement-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort