apiVersion: v1
kind: Service
metadata:
  name: image-app-service
  namespace: gallery-ns
spec: 
  selector:
    app: gallery-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30111
  type: NodePort