apiVersion: v1
kind: Service 
metadata:
  name: hangman-service
  namespace: hangman-ns
spec:
  selector:
    app: hangman-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort